### ISSUE TITLE
"Incoming webhooks" is just a fancy name for HTTP API endpoints

### ISSUE THREAD

**Issue by fiatjaf** [realadeel/awesome-webhooks#9]
In fact most web APIs out there have the ability to handle "incoming webhooks", if you just pass along with these requests an authentication token, either in the body of the request or in a header.

Slack, IFTTT, Zapier and Mattermost, which are currently listed in the "Incoming" section, just happened to use the name "webhook" for what they in fact offer as simple HTTP endpoints that trigger some specific actions inside them.

**Comment by realadeel** [comment]
Thanks for the feedback.
